//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf.Transaction.Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cnblogs.com/frank_xl/", ConfigurationName="ServiceReference.IWCFServiceTransaction1", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IWCFServiceTransaction1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/frank_xl/IWCFServiceTransaction1/AddDataUsingAdapter", ReplyAction="http://www.cnblogs.com/frank_xl/IWCFServiceTransaction1/AddDataUsingAdapterRespon" +
            "se")]
        bool AddDataUsingAdapter(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/frank_xl/IWCFServiceTransaction1/AddDataUsingAdapter", ReplyAction="http://www.cnblogs.com/frank_xl/IWCFServiceTransaction1/AddDataUsingAdapterRespon" +
            "se")]
        System.Threading.Tasks.Task<bool> AddDataUsingAdapterAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceTransaction1Channel : Wcf.Transaction.Client.ServiceReference.IWCFServiceTransaction1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceTransaction1Client : System.ServiceModel.ClientBase<Wcf.Transaction.Client.ServiceReference.IWCFServiceTransaction1>, Wcf.Transaction.Client.ServiceReference.IWCFServiceTransaction1 {
        
        public WCFServiceTransaction1Client() {
        }
        
        public WCFServiceTransaction1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceTransaction1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceTransaction1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceTransaction1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddDataUsingAdapter(string name) {
            return base.Channel.AddDataUsingAdapter(name);
        }
        
        public System.Threading.Tasks.Task<bool> AddDataUsingAdapterAsync(string name) {
            return base.Channel.AddDataUsingAdapterAsync(name);
        }
    }
}
