//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMessageMode_Client.WCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRequestAndResponseModeMessage", ReplyAction="http://tempuri.org/IService/GetRequestAndResponseModeMessageResponse")]
        string GetRequestAndResponseModeMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRequestAndResponseModeMessage", ReplyAction="http://tempuri.org/IService/GetRequestAndResponseModeMessageResponse")]
        System.Threading.Tasks.Task<string> GetRequestAndResponseModeMessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GetSingleModeMessage")]
        void GetSingleModeMessage();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GetSingleModeMessage")]
        System.Threading.Tasks.Task GetSingleModeMessageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WcfMessageMode_Client.WCFServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WcfMessageMode_Client.WCFServiceReference.IService>, WcfMessageMode_Client.WCFServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRequestAndResponseModeMessage() {
            return base.Channel.GetRequestAndResponseModeMessage();
        }
        
        public System.Threading.Tasks.Task<string> GetRequestAndResponseModeMessageAsync() {
            return base.Channel.GetRequestAndResponseModeMessageAsync();
        }
        
        public void GetSingleModeMessage() {
            base.Channel.GetSingleModeMessage();
        }
        
        public System.Threading.Tasks.Task GetSingleModeMessageAsync() {
            return base.Channel.GetSingleModeMessageAsync();
        }
    }
}
