//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wcf.Operation.OverLoad.Client.ServiceOverLoad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOverLoad.IWCFOverLoadingService")]
    public interface IWCFOverLoadingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello1", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello1Response")]
        string SayHello1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello1", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello1Response")]
        System.Threading.Tasks.Task<string> SayHello1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello2", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello2Response")]
        string SayHello2(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello2", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello2Response")]
        System.Threading.Tasks.Task<string> SayHello2Async(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello3", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello3Response")]
        string SayHello3(string firstName, string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFOverLoadingService/SayHello3", ReplyAction="http://tempuri.org/IWCFOverLoadingService/SayHello3Response")]
        System.Threading.Tasks.Task<string> SayHello3Async(string firstName, string lastName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFOverLoadingServiceChannel : Wcf.Operation.OverLoad.Client.ServiceOverLoad.IWCFOverLoadingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFOverLoadingServiceClient : System.ServiceModel.ClientBase<Wcf.Operation.OverLoad.Client.ServiceOverLoad.IWCFOverLoadingService>, Wcf.Operation.OverLoad.Client.ServiceOverLoad.IWCFOverLoadingService {
        
        public WCFOverLoadingServiceClient() {
        }
        
        public WCFOverLoadingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFOverLoadingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFOverLoadingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFOverLoadingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello1() {
            return base.Channel.SayHello1();
        }
        
        public System.Threading.Tasks.Task<string> SayHello1Async() {
            return base.Channel.SayHello1Async();
        }
        
        public string SayHello2(string name) {
            return base.Channel.SayHello2(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHello2Async(string name) {
            return base.Channel.SayHello2Async(name);
        }
        
        public string SayHello3(string firstName, string lastName) {
            return base.Channel.SayHello3(firstName, lastName);
        }
        
        public System.Threading.Tasks.Task<string> SayHello3Async(string firstName, string lastName) {
            return base.Channel.SayHello3Async(firstName, lastName);
        }
    }
}
